// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LateralMenuController from "./lateral_menu_controller"
application.register("lateral-menu", LateralMenuController)

import LinesMapController from "./lines_map_controller"
application.register("lines-map", LinesMapController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapHomeController from "./map_home_controller"
application.register("map-home", MapHomeController)

import SearchRouteController from "./search_route_controller"
application.register("search-route", SearchRouteController)

import SugestionsSearchController from "./sugestions_search_controller"
application.register("sugestions-search", SugestionsSearchController)
